### PR TITLE
Fade time adjust

### PR DESCRIPTION
**Pull request by ssoftcheck**
On ubuntu 19.10 with gnome 3.34 the default 10s fade time seems to stop the screensaver from starting. I added preference to alter this default time. with 11s, the screensaver opens for me and the screen stays on. I am not sure if the timeout still works.

### CODE REVIEW

**Comment by szpak** [comment]
@ssoftcheck Do you observe [that behavior](https://github.com/sunwxg/gnome-shell-extension-unblank/issues/5#issuecomment-475953266) with the blank screen, but without the screen server enabled?

**Comment by ssoftcheck** [comment]
for me screen saver does not start if i cancel it during the dim. however, it will not start at all if i wait. I think the function that does the unblanking needs to wait another second or it pre-empts the screen saver

**Comment by sunwxg** [comment]
My system is openSUSE Tumbleweed GNOME 3.34, this function works well.
During the dim, you can press any key to cancel the dim. After this you wait the time(/org/gnome/desktop/session/idle-delay), system will start a new dimming, after dimming finishes, screen is locked.

**Comment by ssoftcheck** [comment]
The problem I have with the current version is that the screen never locks. Dim will start, then right before screen lock, it becomes normal again, screen is still on, no lock

**Comment by sunwxg** [comment]
Could you try this PR #12

**Pull request closed without merging**
