### PR TITLE
Update for GNOME 3.38

### PR DESCRIPTION
**Pull request by MaxXor**

### CODE REVIEW

**Comment by sunwxg** [comment]
Have you tested it on GNOME 3.38? Now I don't have environment to test it.

**Comment by MaxXor** [comment]
I didn't test yet, just wanted to add the new version to the github repo as it's needed anyways. I will test once Gnome 3.38 hits Arch stable.

**Comment by sunwxg** [comment]
Okay, after we test it on 3.38 I will merge this request.
Thank you.

**Comment by MaxXor** [comment]
Now that 3.38 is in Arch stable I've tested it and didn't notice any errors. Seems to be working?

**Comment by sunwxg** [comment]
Thank you.

**Comment by janvs0** [comment]
Extension didn't work for me on 3.38 due to Tweener not being present in gnome-shell anymore.
removing: https://github.com/sunwxg/gnome-shell-extension-unblank/blob/41bd9e2c574b055964f0a6471e92cb5cc679a787/unblank%40sun.wxg%40gmail.com/extension.js#L16
fixed it.

**Comment by MaxXor** [comment]
@janvs0 Can confirm this. Sorry it seems I didn't test well enough...

**Pull request merged**
